version: '3.8'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  app:
    image: 'url-shortner:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - redis
